### PR TITLE
Update to storm 1.0.0

### PR DESCRIPTION
**Pull request by SamuelBucheliZ**
Hi,
a suggestion for updating to Storm 1.0.0, it compiles, but I haven't tested it any further.

With kind regards

Sam

### CODE REVIEW

**Comment by geoand** [comment]
It would be awesome if this can make it into a Maven release somehow.
Currently anyone using this extremely useful library for Apache Storm is stuck on pre-Storm 1.0.0 versions.

**Comment by pmdcosta** [comment]
Any developments on the ?

**Comment by SamuelBucheliZ** [comment]
@geoand @pmdcosta Considering that the last commits to this repository were 7 months ago, I'm not sure whether it is still under active development. Maybe it's about time to consider a fork? It actually would be great to make this part of https://github.com/apache/storm/tree/master/external as it always struck me as a bit odd that RabbitMQ is missing there (and yet is often used as one of the standard use cases for Storm topology examples...)

**Comment by geoand** [comment]
@SamuelBucheliZ I totally agree with your reasoning!

**Comment by drazzib** [comment]
Hi !
I'll start reviewing proposed PR during this week.
I think that merging this project into Storm External is a relevant suggestion to synchronize this project with Storm releases. cc @ppat what do you think about ?
Regards,

**Comment by ppat** [comment]
I do not actively develop or use Storm or RabbitMQ at the moment. So I support moving this to Storm External as well. @drazzib, you're added as contributor on this project. So feel free to merge PR's that you feel pass the code quality standards that already exist and relevant to this project. 

If and when we get to a place where this is accepted into Storm External, please reach me via email directly if you need my help.

Thanks,
Peter

**Comment by drazzib** [comment]
Thanks for your feedback @ppat, I'll try to merge some PR and propose this project for Storm Externals

**Pull request merged**
